spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=postgres
spring.datasource.password=Th1234!

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

dominio.openapi.dev-url=http://localhost:8080