spring.application.name=biblioteca

server.port=8080

spring.output.ansi.enabled=ALWAYS

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}

spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:anaid30}
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.show-sql=true
spring.jpa.generate.ddl=true
spring.jpa.hibernate.ddl-auto=update

dominio.openapi.dev-url=http://localhost:8080
dominio.openapi.prod-url=https://www.meudominio.com.br
springdoc.swagger-ui.tags-sorter=alpha
api.security.token.secret=senhaAPI

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trabtest.api@gmail.com
spring.mail.password=peejgoykevppvlpm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true